-- 1. CLEANUP
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS name;
DROP TABLE IF EXISTS user_name;
DROP TABLE IF EXISTS profile_photo;
DROP TABLE IF EXISTS profile_banner;
DROP TABLE IF EXISTS bio;
DROP TABLE IF EXISTS bio_links;
DROP TABLE IF EXISTS user_number;
DROP TABLE IF EXISTS user_email;
DROP TABLE IF EXISTS user_country;
DROP TABLE IF EXISTS user_dob;
SET FOREIGN_KEY_CHECKS = 1;

-- 2. CREATE THE MAIN PROFILE TABLE
CREATE TABLE profile (
    v_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    p_p_id BIGINT UNSIGNED NULL, 
    p_b_id BIGINT UNSIGNED NULL, 
    v_n_id BIGINT UNSIGNED NULL, 
    v_name_id BIGINT UNSIGNED NULL, 
    v_bio_id BIGINT UNSIGNED NULL, 
    v_bl_id BIGINT UNSIGNED NULL,
    u_num_id BIGINT UNSIGNED NULL,   -- New Link
    u_email_id BIGINT UNSIGNED NULL, -- New Link
    u_c_id BIGINT UNSIGNED NULL,     -- New Link
    p_dob_id BIGINT UNSIGNED NULL,   -- New Link
    v_status INT DEFAULT 0,
    v_created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 3. CREATE COMPONENT TABLES (History/Details)

CREATE TABLE user_number (
    u_num_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    u_number VARCHAR(20) NOT NULL,
    u_num_status INT DEFAULT 0,
    u_num_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    u_num_verification_status INT DEFAULT 0,
    CONSTRAINT fk_owner_number FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE user_email (
    u_email_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    u_emailber VARCHAR(255) NOT NULL, -- Matched column name from your CSV
    u_email_status INT DEFAULT 0,
    u_email_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    u_email_verification_status INT DEFAULT 0,
    CONSTRAINT fk_owner_email FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE user_country (
    u_c_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    u_country VARCHAR(100) NOT NULL,
    u_c_status INT DEFAULT 0,
    u_c_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_country FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE user_dob (
    p_dob_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    p_dob DATE NOT NULL,
    p_dob_status INT DEFAULT 0,
    p_dob_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_dob FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- (Remaining tables from previous steps)
CREATE TABLE name (
    v_name_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    v_name_name TEXT NOT NULL,
    v_name_status INT DEFAULT 0,
    v_name_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_name FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE user_name (
    v_n_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    v_n_name TEXT NOT NULL,
    v_n_status INT DEFAULT 0,
    v_n_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_username FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE profile_photo (
    p_p_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    p_p VARCHAR(511) NOT NULL,
    p_p_status INT DEFAULT 0,
    p_p_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_photo FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE profile_banner (
    p_b_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    p_b VARCHAR(511) NOT NULL,
    p_b_status INT DEFAULT 0,
    p_b_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_banner FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE bio (
    v_bio_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    v_bio_name TEXT NOT NULL,
    v_bio_status INT DEFAULT 0,
    v_bio_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_bio FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE bio_links (
    v_bl_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    v_id BIGINT UNSIGNED NOT NULL,
    v_bl_name TEXT NOT NULL,
    v_bl_status INT DEFAULT 0,
    v_bl_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_biolinks FOREIGN KEY (v_id) REFERENCES profile(v_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 4. ADD ACTIVE POINTER CONSTRAINTS
ALTER TABLE profile ADD CONSTRAINT fk_active_photo FOREIGN KEY (p_p_id) REFERENCES profile_photo(p_p_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_banner FOREIGN KEY (p_b_id) REFERENCES profile_banner(p_b_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_user_name FOREIGN KEY (v_n_id) REFERENCES user_name(v_n_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_display_name FOREIGN KEY (v_name_id) REFERENCES name(v_name_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_bio FOREIGN KEY (v_bio_id) REFERENCES bio(v_bio_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_bio_links FOREIGN KEY (v_bl_id) REFERENCES bio_links(v_bl_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_number FOREIGN KEY (u_num_id) REFERENCES user_number(u_num_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_email FOREIGN KEY (u_email_id) REFERENCES user_email(u_email_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_country FOREIGN KEY (u_c_id) REFERENCES user_country(u_c_id) ON DELETE SET NULL;
ALTER TABLE profile ADD CONSTRAINT fk_active_dob FOREIGN KEY (p_dob_id) REFERENCES user_dob(p_dob_id) ON DELETE SET NULL;